"""expand emoji_cover length to 255

Revision ID: b7c9f2e9f1d2
Revises: 5a1b2c3d4e5f
Create Date: 2025-09-07 00:00:00.000000
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b7c9f2e9f1d2'
down_revision = '5a1b2c3d4e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'emoji_cover',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'emoji_cover',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    # ### end Alembic commands ###
